# Generated by Django 4.2.11 on 2024-03-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwk1site', '0002_authors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='user',
        ),
    ]
