# Generated by Django 4.2.11 on 2024-03-27 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cwk1site', '0003_remove_authors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='username',
        ),
        migrations.AddField(
            model_name='authors',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
