# Generated by Django 4.2.11 on 2024-03-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwk1site', '0004_remove_authors_password_remove_authors_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='user',
            new_name='user_id',
        ),
    ]
