# Generated by Django 4.2.11 on 2024-03-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwk1site', '0005_rename_user_authors_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='user_id',
            new_name='user',
        ),
    ]
